CREATE TABLE tbl_testimoni (
    id INT PRIMARY KEY AUTO_INCREMENT,
    slug VARCHAR(100),
    name VARCHAR(100),
    star INT,
    testimoni TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (slug) REFERENCES tbl_order(slug) ON DELETE CASCADE ON UPDATE CASCADE
);
