CREATE TABLE tbl_guest (
    id INT PRIMARY KEY AUTO_INCREMENT,
    slug VARCHAR(100),
    name VARCHAR(100),
    phone VARCHAR(15),
    view INT,
    confirm VARCHAR(20),
    number_of_guest INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (slug) REFERENCES tbl_order(slug) ON DELETE CASCADE ON UPDATE CASCADE
);
