CREATE TABLE tbl_user (
    id INT PRIMARY KEY AUTO_INCREMENT,
    access VARCHAR(6),
    roles VARCHAR(100) DEFAULT "USER",
    name VARCHAR(100),
    slug VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (slug) REFERENCES tbl_order(slug) ON DELETE CASCADE ON UPDATE CASCADE
);
